//
// StoreAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class StoreAPI {
    /**
     Delete purchase order by ID
     - DELETE /store/order/{orderId}
     - For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
     - parameter orderId: (path) ID of the order that needs to be deleted 
     - returns: RequestProvider<Void> 
     */
    open class func deleteOrder(orderId: Int64) -> RequestProvider<Void> {
        var path = "/store/order/{orderId}"
        let orderIdPreEscape = "\(orderId)"
        let orderIdPostEscape = orderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{orderId}", with: orderIdPostEscape, options: .literal, range: nil)
        
        return RequestProvider<Void>(endpoint: path, method: "DELETE")
    }

    /**
     Returns pet inventories by status
     - GET /store/inventory
     - Returns a map of status codes to quantities
     - API Key:
       - type: apiKey api_key 
       - name: api_key
     - returns: RequestProvider<[String:Int]> 
     */
    open class func getInventory() -> RequestProvider<[String:Int]> {
        let path = "/store/inventory"
        
        return RequestProvider<[String:Int]>(endpoint: path, method: "GET")
    }

    /**
     Find purchase order by ID
     - GET /store/order/{orderId}
     - For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
     - parameter orderId: (path) ID of pet that needs to be fetched 
     - returns: RequestProvider<Order> 
     */
    open class func getOrderById(orderId: Int64) -> RequestProvider<Order> {
        var path = "/store/order/{orderId}"
        let orderIdPreEscape = "\(orderId)"
        let orderIdPostEscape = orderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{orderId}", with: orderIdPostEscape, options: .literal, range: nil)
        
        return RequestProvider<Order>(endpoint: path, method: "GET")
    }

    /**
     Place an order for a pet
     - POST /store/order
     - parameter order: (body) order placed for purchasing the pet 
     - returns: RequestProvider<Order> 
     */
    open class func placeOrder(order: Order) -> RequestProvider<Order> {
        let path = "/store/order"
        let parameters = order

        return RequestProvider<Order>(endpoint: path, method: "POST", parameters: RequestProvider.Parameters(parameters))
    }

}
